package ir.ahe.abbas.bluetoothchat.core.data.osdatasource

enum class BluetoothDeviceType(val value: Int, val shortName: String) {
    AUDIO_VIDEO_CAMCORDER(1076, "avcamcorder"),
    AUDIO_VIDEO_CAR_AUDIO(1056, "caraudio"),
    AUDIO_VIDEO_HANDSFREE(1032, "handsfree"),
    AUDIO_VIDEO_HEADPHONES(1048, "headphones"),
    AUDIO_VIDEO_HIFI_AUDIO(1064, "hifiaudio"),
    AUDIO_VIDEO_LOUDSPEAKER(1044, "loudspeaker"),
    AUDIO_VIDEO_MICROPHONE(1040, "microphone"),
    AUDIO_VIDEO_PORTABLE_AUDIO(1052, "portableaudio"),
    AUDIO_VIDEO_SET_TOP_BOX(1060, "settopbox"),
    AUDIO_VIDEO_UNCATEGORIZED(1024, "uncategorized_av"),
    AUDIO_VIDEO_VCR(1068, "vcr"),
    AUDIO_VIDEO_VIDEO_CAMERA(1072, "videocamera"),
    AUDIO_VIDEO_VIDEO_CONFERENCING(1088, "videoconferencing"),
    AUDIO_VIDEO_VIDEO_DISPLAY_AND_LOUDSPEAKER(1084, "display_loudspeaker"),
    AUDIO_VIDEO_VIDEO_GAMING_TOY(1096, "gamingtoy"),
    AUDIO_VIDEO_VIDEO_MONITOR(1080, "videomonitor"),
    AUDIO_VIDEO_WEARABLE_HEADSET(1028, "wearableheadset"),
    COMPUTER_DESKTOP(260, "desktop"),
    COMPUTER_HANDHELD_PC_PDA(272, "handheldpcpda"),
    COMPUTER_LAPTOP(268, "laptop"),
    COMPUTER_PALM_SIZE_PC_PDA(276, "palmsizepcpda"),
    COMPUTER_SERVER(264, "server"),
    COMPUTER_UNCATEGORIZED(256, "uncategorized_pc"),
    COMPUTER_WEARABLE(280, "wearablepc"),
    HEALTH_BLOOD_PRESSURE(2308, "bloodpressure"),
    HEALTH_DATA_DISPLAY(2332, "datadisplay"),
    HEALTH_GLUCOSE(2320, "glucose"),
    HEALTH_PULSE_OXIMETER(2324, "pulseoximeter"),
    HEALTH_PULSE_RATE(2328, "pulserate"),
    HEALTH_THERMOMETER(2312, "thermometer"),
    HEALTH_UNCATEGORIZED(2304, "uncategorized_health"),
    HEALTH_WEIGHING(2316, "weighing"),
    PERIPHERAL_KEYBOARD(1344, "keyboard"),
    PERIPHERAL_KEYBOARD_POINTING(1472, "keyboardpointing"),
    PERIPHERAL_NON_KEYBOARD_NON_POINTING(1280, "nonkeyboardpointing"),
    PERIPHERAL_POINTING(1408, "pointing"),
    PHONE_CELLULAR(516, "phone cellular"),
    PHONE_CORDLESS(520, "phone cordless"),
    PHONE_ISDN(532, "phone isdn"),
    PHONE_MODEM_OR_GATEWAY(528, " phone modemorgateway"),
    PHONE_SMART(524, "smartphone"),
    PHONE_UNCATEGORIZED(512, "uncategorized_phone"),
    TOY_CONTROLLER(2064, "controller"),
    TOY_DOLL_ACTION_FIGURE(2060, "dollactionfigure"),
    TOY_GAME(2068, "game"),
    TOY_ROBOT(2052, "robot"),
    TOY_UNCATEGORIZED(2048, "uncategorized_toy"),
    TOY_VEHICLE(2056, "vehicle"),
    WEARABLE_GLASSES(1812, "glasses"),
    WEARABLE_HELMET(1808, "helmet"),
    WEARABLE_JACKET(1804, "jacket"),
    WEARABLE_PAGER(1800, "pager"),
    WEARABLE_UNCATEGORIZED(1792, "uncategorized_wearable"),
    WEARABLE_WRIST_WATCH(1796, "wristwatch");

    companion object {
        fun findByValue(value: Int): BluetoothDeviceType {
            return values().find { it.value == value } ?: PHONE_SMART
        }
    }
}
